name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint
        run: |
          ruff check src/neo
      - name: Type Check
        run: |
          mypy src/neo
      - name: Tests
        run: |
          pytest -q
      - name: Build image
        run: |
          docker build -t neo-api:ci .
